name: ci

on:
pull_request:
  branches: [main]
push:
  branches: [main]
  tags:
  - '*'


jobs:
  rust:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      GH_ACTIONS: 1
      RUST_BACKTRACE: full
      RUSTFLAGS: -D warnings

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy,rustfmt

      - name: Format
        run: cargo fmt --all --check

      - name: Lint
        run: cargo clippy --all-targets --all-features --release

      - name: Test
        run: cargo test --release --all-targets --all-features

      - name: Build
        run: cargo build --release --all-targets --all-features

      - name: Publish
        if: |
          github.repository == 'denoland/flaky_test' &&
          startsWith(github.ref, 'refs/tags/')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
