name: ci

on: [push, pull_request]

jobs:
  rust:
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'denoland:')
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy,rustfmt

      - name: Build
        run: cargo build --release --all-targets

      - name: Test
        run: cargo test --release --all-targets

      - name: Lint
        run: cargo clippy --all-targets
